name: Sync issue to Azure DevOps work item (testing)

on:
  issues:
    types:
      [ opened, labeled ]
jobs:
  create_issues:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Check if artifact exists
      id: check-artifact
      uses: actions/upload-artifact@v2
      with:
        name: pager_duty_issues.txt
      continue-on-error: true

    - name: Create artifact if it doesn't exist
      if: ${{ failure() }}
      run: |
        echo "Creating pager_duty_issues.txt"
        # Add code here to create the YAML file and add it to the artifact

    - name: Check if issue URL exists
      id: check-issue
      run: |
        if grep -q '${{ github.event.issue.html_url }}' pager_duty_issues.txt; then
          echo "Issue URL exists"
          exit 0
        else
          echo "Issue URL does not exist"
          # Add code here to run the script that creates a new issue with the specified URL
          echo '${{ github.event.issue.html_url }}' >> pager_duty_issues.txt
        fi
    
    - if: contains(github.event.issue.labels.*.name, 'pager-duty')
      name: custom issues
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD }}
        DISCORD_WEBHOOK_FORUM: ${{ secrets.DISCORD_FORUM }}
        DISCORD_FORUM_CHANNEL_ID: ${{ secrets.DISCORD_FORUM_CHANNEL_ID }}
        ENABLE_FORUM: true

      uses: jatin-jangir/action-discord@master
      with:
        args: " ${{ github.event.issue.title }} ${{ github.event.issue.html_url }}"
