name: Sync issue to Azure DevOps work item (testing)

on:
  issues:
    types:
      [ opened ]
jobs:
  create_issues:
    runs-on: ubuntu-latest
    steps:
      - if: contains(github.event.issue.labels.*.name, 'pager-duty')
        name: custom issues
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD }}
          DISCORD_WEBHOOK_FORUM: ${{ secrets.DISCORD_FORUM }}
          DISCORD_FORUM_CHANNEL_ID: ${{ secrets.DISCORD_FORUM_CHANNEL_ID }}
          ENABLE_FORUM: true
          
        uses: jatin-jangir/action-discord@master
        with:
          args: " ${{ github.event.issue.title}} ${{github.event.issue.html_url}}"
