name: Sync issue to Azure DevOps work item (testing)

on:
  issues:
    types:
      [ opened, edited, deleted, closed, reopened, labeled ]
jobs:
  create_issues:
    runs-on: ubuntu-latest
    steps:
    - if: github.event.label.name == 'pager-duty'
      name: custom issues
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD }}
        DISCORD_WEBHOOK_FORUM: ${{ secrets.DISCORD_FORUM }}
        ENABLE_FORUM: true

      uses: devtron-labs/action-discord@master
      with:
        args: " ${{ github.event.issue.title }} ${{ github.event.issue.html_url }}"
